Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # VirtualBox.
  config.vm.define :centos do |node|
    node.vm.hostname = "test-01"
    node.vm.box = "file://builds/libvirt-mentos7.box"

    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.storage_pool_name = "local"
      libvirt.graphics_type = "vnc"
      libvirt.graphics_port = 59001
      libvirt.graphics_ip = '0.0.0.0'
      libvirt.memory = 1024
      libvirt.cpus = 2
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
